version: "3.9"

services:
  fastapi-container:
    build:
      context: .
    ports:
    - "8000:8000"
    volumes:
    - ./sistema_recomendacao_endpoint:/app/sistema_recomendacao_endpoint
    container_name: fastapi-container
    command: ["uvicorn", "sistema_recomendacao_endpoint.api_sistema_recomendacao:app", "--reload", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
